const express = require('express')
const app = express()
const path = require('path')

// static files are files that aren't generated by the server
// use middleware to serve that public folder
app.use(express.static(`public`))

app.get('/',(req,res) => {
    res.sendFile(path.join(__dirname,'../public/index.html'))
})

app.listen(4000, () => console.log(`server running on 4000`))