const express = require('express')
const app = express()

// static files are files that aren't generated by the server
// use middleware to serve that public folder
app.use(express.static(`${__dirname}/public`)) // dirname variable is whatever the directory name is

app.listen(400, () => console.log('server running on 4000'))